# Generated by Django 2.0.5 on 2018-05-23 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Seg', 'Segunda'), ('Ter', 'Terca'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sabado'), ('Dom', 'Domingo')], help_text='Obrigatório.', max_length=3)),
                ('horario_inicio', models.CharField(help_text='Obrigatório.', max_length=5)),
                ('horario_fim', models.CharField(help_text='Obrigatório.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_final', models.DateField()),
                ('tipo_aviso', models.CharField(choices=[('N', 'Aviso'), ('H', 'Tarefa'), ('W', 'Trabalho'), ('E', 'Prova')], help_text='Obrigatório.', max_length=1)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('ultima_modificacao', models.DateField(auto_now=True)),
                ('data_post', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório.', max_length=240)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório.', max_length=120)),
                ('local', models.CharField(help_text='Obrigatório.', max_length=120)),
                ('dia', models.CharField(choices=[('Seg', 'Segunda'), ('Ter', 'Terca'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sabado'), ('Dom', 'Domingo')], help_text='Obrigatório.', max_length=3)),
                ('horario_inicio', models.CharField(max_length=5)),
                ('horario_fim', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório.', max_length=120)),
                ('email', models.EmailField(help_text='Obrigatório.', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório.', max_length=120)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(help_text='Obrigatório', related_name='alunos_matriculados', to=settings.AUTH_USER_MODEL)),
                ('colegio', models.ForeignKey(help_text='Obrigatório.', on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Colegio')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Professor'),
        ),
        migrations.AddField(
            model_name='materia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Turma'),
        ),
        migrations.AddField(
            model_name='avisos',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Materia'),
        ),
        migrations.AddField(
            model_name='avisos',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Turma'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='professor',
            field=models.ForeignKey(help_text='Obrigatório.', on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Professor'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='turma',
            field=models.ForeignKey(help_text='Obrigatório.', on_delete=django.db.models.deletion.PROTECT, to='classmanagement.Turma'),
        ),
    ]
