# Generated by Django 2.0.5 on 2018-05-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avisos',
            new_name='Aviso',
        ),
        migrations.AlterModelOptions(
            name='colegio',
            options={'verbose_name': 'Colégio', 'verbose_name_plural': 'Colégios'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
    ]
